In [5]:
import pandas as pd

df1 = pd.read_excel("/dataset(top).xlsx")
df2 = pd.read_csv("/dataset(qs).csv")

In [6]:
print("Dataset 1:")
display(df1.head())

print("Dataset 2:")
display(df2.head())

Dataset 1:

,Rank,Dense Rank,University Name,Location Full,Overall Score,Teaching,Research Environment,Research Quality,Industry,International Outlook,No. of FTE Students,No. of Students per Staff,International Students
0,1,1,University of Oxford,United Kingdom,98.5,96.8,100.0,98.8,99.6,97.3,22095,10.8,0.43
1,2,2,Massachusetts Institute of Technology,United States,98.1,99.2,96.0,99.7,100.0,93.8,11836,8.0,0.33
2,3,3,Harvard University,United States,97.7,97.3,99.9,99.3,85.7,90.1,22584,10.0,0.25
3,4,4,Princeton University,United States,97.5,98.3,98.0,98.9,96.9,87.4,8378,7.8,0.23
4,5,5,University of Cambridge,United Kingdom,97.4,95.9,99.9,97.6,88.4,97.1,20980,11.5,0.38

Dataset 2:

,2025 Rank,2024 Rank,University Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability,Overall Score
0,1,1,Massachusetts Institute of Technology (MIT),US,United States,M,100.0,100.0,100.0,100.0,99.3,86.8,96.0,100.0,99.0,100
1,2,6,Imperial College London,UK,United Kingdom,L,98.5,99.5,98.2,93.9,100.0,99.6,97.4,93.4,99.7,98.5
2,3,3,University of Oxford,UK,United Kingdom,L,100.0,100.0,100.0,84.8,98.1,97.7,100.0,100.0,85.0,96.9
3,4,4,Harvard University,US,United States,L,100.0,100.0,96.3,100.0,74.1,69.0,99.6,100.0,84.4,96.8
4,5,2,University of Cambridge,UK,United Kingdom,L,100.0,100.0,100.0,84.6,100.0,94.8,99.3,100.0,84.8,96.7

In [7]:
print("Dataset 1:")
df1.info()

print("\nDataset 2:")
df2.info()

Dataset 1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Rank                       200 non-null    int64
 1   Dense Rank                 200 non-null    int64
 2   University Name            200 non-null    object
 3   Location Full              200 non-null    object
 4   Overall Score              200 non-null    float64
 5   Teaching                   200 non-null    float64
 6   Research Environment       200 non-null    float64
 7   Research Quality           200 non-null    float64
 8   Industry                   200 non-null    float64
 9   International Outlook      200 non-null    float64
 10  No. of FTE Students        200 non-null    int64
 11  No. of Students per Staff  200 non-null    float64
 12  International Students     200 non-null    float64
dtypes: float64(8), int64(3), object(2)
memory usage: 20.4+ KB

Dataset 2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   2025 Rank                       1503 non-null   object
 1   2024 Rank                       1482 non-null   object
 2   University  Name                1503 non-null   object
 3   Location                        1503 non-null   object
 4   Location Full                   1503 non-null   object
 5   Size                            1503 non-null   object
 6   Academic Reputation             1503 non-null   float64
 7   Employer Reputation             1503 non-null   float64
 8   Faculty Student                 1503 non-null   float64
 9   Citations per Faculty           1503 non-null   float64
 10  International Faculty           1403 non-null   float64
 11  International Students          1445 non-null   float64
 12  International Research Network  1502 non-null   float64
 13  Employment Outcomes             1503 non-null   float64
 14  Sustainability                  1484 non-null   float64
 15   Overall Score                  1503 non-null   object
dtypes: float64(9), object(7)
memory usage: 188.0+ KB

In [8]:
print(df1.columns)
print(df2.columns)

Index(['Rank', 'Dense Rank', 'University Name', 'Location Full',
       'Overall Score', 'Teaching', 'Research Environment', 'Research Quality',
       'Industry', 'International Outlook', 'No. of FTE Students',
       'No. of Students per Staff', 'International Students'],
      dtype='object')
Index(['2025 Rank', '2024 Rank', 'University  Name', 'Location',
       'Location Full', 'Size', 'Academic Reputation', 'Employer Reputation',
       'Faculty Student', 'Citations per Faculty', 'International Faculty',
       'International Students', 'International Research Network',
       'Employment Outcomes', 'Sustainability', ' Overall Score'],
      dtype='object')

In [9]:
print("Dataset 1 missing values:")
print(df1.isnull().sum())

print("\nDataset 2 missing values:")
print(df2.isnull().sum())

Dataset 1 missing values:
Rank                         0
Dense Rank                   0
University Name              0
Location Full                0
Overall Score                0
Teaching                     0
Research Environment         0
Research Quality             0
Industry                     0
International Outlook        0
No. of FTE Students          0
No. of Students per Staff    0
International Students       0
dtype: int64

Dataset 2 missing values:
2025 Rank                           0
2024 Rank                          21
University  Name                    0
Location                            0
Location Full                       0
Size                                0
Academic Reputation                 0
Employer Reputation                 0
Faculty Student                     0
Citations per Faculty               0
International Faculty             100
International Students             58
International Research Network      1
Employment Outcomes                 0
Sustainability                     19
 Overall Score                      0
dtype: int64

In [10]:
print("Dataset 1 duplicates:", df1.duplicated().sum())
print("Dataset 2 duplicates:", df2.duplicated().sum())

Dataset 1 duplicates: 0
Dataset 2 duplicates: 0

In [11]:
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

In [13]:
print(df1.dtypes)
print("\nDataset 2:")
print(df2.dtypes)

Rank                           int64
Dense Rank                     int64
University Name               object
Location Full                 object
Overall Score                float64
Teaching                     float64
Research Environment         float64
Research Quality             float64
Industry                     float64
International Outlook        float64
No. of FTE Students            int64
No. of Students per Staff    float64
International Students       float64
dtype: object

Dataset 2:
2025 Rank                          object
2024 Rank                          object
University  Name                   object
Location                           object
Location Full                      object
Size                               object
Academic Reputation               float64
Employer Reputation               float64
Faculty Student                   float64
Citations per Faculty             float64
International Faculty             float64
International Students            float64
International Research Network    float64
Employment Outcomes               float64
Sustainability                    float64
Overall Score                      object
dtype: object

In [16]:
# Clean column names properly
df1.columns = (
    df1.columns
    .astype(str)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

df2.columns = (
    df2.columns
    .astype(str)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

print("Dataset 1 columns:")
print(df1.columns.tolist())

print("\nDataset 2 columns:")
print(df2.columns.tolist())

Dataset 1 columns:
['Rank', 'Dense Rank', 'University Name', 'Location Full', 'Overall Score', 'Teaching', 'Research Environment', 'Research Quality', 'Industry', 'International Outlook', 'No. of FTE Students', 'No. of Students per Staff', 'International Students']

Dataset 2 columns:
['2025 Rank', '2024 Rank', 'University Name', 'Location', 'Location Full', 'Size', 'Academic Reputation', 'Employer Reputation', 'Faculty Student', 'Citations per Faculty', 'International Faculty', 'International Students', 'International Research Network', 'Employment Outcomes', 'Sustainability', 'Overall Score']

In [17]:
# Check the exact University Name column
print("Dataset 1 University column:")
print([col for col in df1.columns if "University" in col])

print("\nDataset 2 University column:")
print([col for col in df2.columns if "University" in col])

Dataset 1 University column:
['University Name']

Dataset 2 University column:
['University Name']

In [18]:
common_universities = set(df1["University Name"]) & set(df2["University Name"])

print("Number of common universities:", len(common_universities))

Number of common universities: 122

In [19]:
# Clean University Name values
df1["University Name"] = (
    df1["University Name"]
    .astype(str)
    .str.strip()
)

df2["University Name"] = (
    df2["University Name"]
    .astype(str)
    .str.strip()
)

print("University names cleaned successfully.")

University names cleaned successfully.

In [20]:
df2["Overall Score"] = pd.to_numeric(
    df2["Overall Score"],
    errors="coerce"
)

print(df2["Overall Score"].dtype)

float64

In [21]:
# Columns where missing numerical values need to be handled
numeric_columns = [
    "International Faculty",
    "International Students",
    "International Research Network",
    "Sustainability"
]

# Fill missing values with the median
for column in numeric_columns:
    df2[column] = df2[column].fillna(df2[column].median())

In [22]:
print("Dataset 1 missing values:")
print(df1.isnull().sum())

print("\nDataset 2 missing values:")
print(df2.isnull().sum())

Dataset 1 missing values:
Rank                         0
Dense Rank                   0
University Name              0
Location Full                0
Overall Score                0
Teaching                     0
Research Environment         0
Research Quality             0
Industry                     0
International Outlook        0
No. of FTE Students          0
No. of Students per Staff    0
International Students       0
dtype: int64

Dataset 2 missing values:
2025 Rank                           0
2024 Rank                          21
University Name                     0
Location                            0
Location Full                       0
Size                                0
Academic Reputation                 0
Employer Reputation                 0
Faculty Student                     0
Citations per Faculty               0
International Faculty               0
International Students              0
International Research Network      0
Employment Outcomes                 0
Sustainability                      0
Overall Score                     903
dtype: int64

In [23]:
print(df2["Overall Score"].head(20))

0     100.0
1      98.5
2      96.9
3      96.8
4      96.7
5      96.1
6      93.9
7      93.7
8      91.6
9      90.9
10     90.3
11     90.1
12     88.9
13     88.5
14     88.4
15     87.9
16     87.6
17     87.3
18     87.1
19     86.5
Name: Overall Score, dtype: float64

In [25]:
# Reload the original Dataset 2
df2_original = pd.read_excel("/dataset(top).xlsx")

print(df2_original["Overall Score"].dtype)
print(df2_original["Overall Score"].head(20))

float64
0     98.5
1     98.1
2     97.7
3     97.5
4     97.4
5     97.2
6     96.3
7     94.5
8     94.4
9     94.1
10    93.0
11    92.5
12    92.0
13    90.9
14    90.9
15    90.7
16    89.9
17    89.8
18    89.8
19    89.2
Name: Overall Score, dtype: float64

In [26]:
# Find values that cannot be converted to numbers
temp_score = pd.to_numeric(
    df2_original["Overall Score"],
    errors="coerce"
)

invalid_scores = df2_original.loc[
    temp_score.isna(),
    "Overall Score"
]

print("Number of invalid/missing Overall Score values:",
      invalid_scores.shape[0])

print("\nValues found:")
print(invalid_scores.value_counts(dropna=False).head(20))

Number of invalid/missing Overall Score values: 0

Values found:
Series([], Name: count, dtype: int64)

In [31]:
import pandas as pd

# Dataset 1 - QS
df1 = pd.read_excel("/dataset(top).xlsx")

# Dataset 2 - THE
df2 = pd.read_csv("/dataset(qs).csv")

print("Dataset 1 shape:", df1.shape)
print("Dataset 2 shape:", df2.shape)

Dataset 1 shape: (200, 13)
Dataset 2 shape: (1503, 16)

In [33]:
print("Dataset 1 missing values:")
print(df1.isnull().sum())

print("\nDataset 2 missing values:")
print(df2.isnull().sum())

Dataset 1 missing values:
Rank                         0
Dense Rank                   0
University Name              0
Location Full                0
Overall Score                0
Teaching                     0
Research Environment         0
Research Quality             0
Industry                     0
International Outlook        0
No. of FTE Students          0
No. of Students per Staff    0
International Students       0
dtype: int64

Dataset 2 missing values:
2025 Rank                           0
2024 Rank                          21
University  Name                    0
Location                            0
Location Full                       0
Size                                0
Academic Reputation                 0
Employer Reputation                 0
Faculty Student                     0
Citations per Faculty               0
International Faculty             100
International Students             58
International Research Network      1
Employment Outcomes                 0
Sustainability                     19
 Overall Score                      0
dtype: int64

In [34]:
missing_columns = [
    "International Faculty",
    "International Students",
    "International Research Network",
    "Sustainability"
]

for column in missing_columns:
    df2[column] = df2[column].fillna(df2[column].median())

In [35]:
print("Dataset 1 missing values:")
print(df1.isnull().sum().sum())

print("\nDataset 2 missing values:")
print(df2.isnull().sum())

Dataset 1 missing values:
0

Dataset 2 missing values:
2025 Rank                          0
2024 Rank                         21
University  Name                   0
Location                           0
Location Full                      0
Size                               0
Academic Reputation                0
Employer Reputation                0
Faculty Student                    0
Citations per Faculty              0
International Faculty              0
International Students             0
International Research Network     0
Employment Outcomes                0
Sustainability                     0
 Overall Score                     0
dtype: int64

In [37]:
# Clean column names
df1.columns = (
    df1.columns.astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

df2.columns = (
    df2.columns.astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

print("Dataset 1 columns:")
print(df1.columns.tolist())

print("\nDataset 2 columns:")
print(df2.columns.tolist())

Dataset 1 columns:
['Rank', 'Dense Rank', 'University Name', 'Location Full', 'Overall Score', 'Teaching', 'Research Environment', 'Research Quality', 'Industry', 'International Outlook', 'No. of FTE Students', 'No. of Students per Staff', 'International Students']

Dataset 2 columns:
['2025 Rank', '2024 Rank', 'University Name', 'Location', 'Location Full', 'Size', 'Academic Reputation', 'Employer Reputation', 'Faculty Student', 'Citations per Faculty', 'International Faculty', 'International Students', 'International Research Network', 'Employment Outcomes', 'Sustainability', 'Overall Score']

In [38]:
print("Dataset 1 university-related columns:")
print([col for col in df1.columns if "university" in col.lower()])

print("\nDataset 2 university-related columns:")
print([col for col in df2.columns if "university" in col.lower()])

Dataset 1 university-related columns:
['University Name']

Dataset 2 university-related columns:
['University Name']

In [39]:
df1["University Name"] = (
    df1["University Name"]
    .astype(str)
    .str.strip()
)

df2["University Name"] = (
    df2["University Name"]
    .astype(str)
    .str.strip()
)

In [40]:
common_universities = set(df1["University Name"]) & set(df2["University Name"])

print("Number of common universities:", len(common_universities))

Number of common universities: 127

In [41]:
print("Dataset 1 rows:", len(df1))
print("Dataset 2 rows:", len(df2))

common_universities = set(df1["University Name"]) & set(df2["University Name"])

print("Common universities:", len(common_universities))

Dataset 1 rows: 200
Dataset 2 rows: 1503
Common universities: 127

In [42]:
merged_df = pd.merge(
    df1,
    df2,
    on="University Name",
    how="inner",
    suffixes=("_QS", "_THE")
)

In [43]:
print("Merged dataset shape:", merged_df.shape)

Merged dataset shape: (127, 28)

In [44]:
print("Number of universities in merged dataset:",
      merged_df["University Name"].nunique())

Number of universities in merged dataset: 127

In [45]:
display(merged_df.head())

,Rank,Dense Rank,University Name,Location Full_QS,Overall Score_QS,Teaching,Research Environment,Research Quality,Industry,International Outlook,...,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students_THE,International Research Network,Employment Outcomes,Sustainability,Overall Score_THE
0,1,1,University of Oxford,United Kingdom,98.5,96.8,100.0,98.8,99.6,97.3,...,100.0,100.0,100.0,84.8,98.1,97.7,100.0,100.0,85.0,96.9
1,3,3,Harvard University,United States,97.7,97.3,99.9,99.3,85.7,90.1,...,100.0,100.0,96.3,100.0,74.1,69.0,99.6,100.0,84.4,96.8
2,4,4,Princeton University,United States,97.5,98.3,98.0,98.9,96.9,87.4,...,99.8,98.3,57.0,100.0,9.6,56.6,78.3,95.7,51.5,85.5
3,5,5,University of Cambridge,United Kingdom,97.4,95.9,99.9,97.6,88.4,97.1,...,100.0,100.0,100.0,84.6,100.0,94.8,99.3,100.0,84.8,96.7
4,6,6,Stanford University,United States,97.2,97.5,97.3,99.6,100.0,85.1,...,100.0,100.0,100.0,99.0,70.3,60.8,96.8,100.0,81.2,96.1

In [48]:
merged_df.to_excel(
    "/content/cleaned_merged_university_rankings.xlsx",
    index=False
)

print("File created successfully!")

File created successfully!

In [49]:
import os

print(os.getcwd())
print(os.listdir())

/content
['.config', 'cleaned_merged_university_rankings.xlsx', 'sample_data']

In [50]:
from google.colab import files

files.download("/content/cleaned_merged_university_rankings.xlsx")