In [5]:
import pandas as pd

In [32]:
df = pd.read_csv("university_raw_data.csv")

In [7]:
import os
os.getcwd()

'C:\\Users\\dell'

In [8]:
df = pd.read_csv("university_raw_data.csv")

In [9]:
df.head()

,RANK_2025,RANK_2024,University,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,Sustainability_Score,Sustainability_Rank,Overall_Score,Overall Teaching Score,Research Score,Research Quality,Industry Income Score,International Outlook Score,Overall Score,Rank
0,1,1,Massachusetts Institute of Technology (MIT),United States,Americas,M,CO,VH,B,100.0,...,99.0,15=,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,6,Imperial College London,United Kingdom,Europe,L,FC,VH,A,98.5,...,99.7,6,98.5,89.3,94.9,98.5,90.8,98.3,94.36,8.0
2,3,3,University of Oxford,United Kingdom,Europe,L,FC,VH,A,100.0,...,85.0,126,96.9,96.8,100.0,98.8,99.6,97.3,98.50,1.0
3,4,4,Harvard University,United States,Americas,L,FC,VH,B,100.0,...,84.4,130,96.8,97.3,99.9,99.3,85.7,90.1,94.46,7.0
4,5,2,University of Cambridge,United Kingdom,Europe,L,FC,VH,A,100.0,...,84.8,127=,96.7,95.9,99.9,97.6,88.4,97.1,95.78,6.0

In [10]:
df.shape

(1503, 35)

In [11]:
df.shape
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 35 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   RANK_2025                             1503 non-null   str
 1   RANK_2024                             1482 non-null   str
 2   University                            1503 non-null   str
 3   Location                              1503 non-null   str
 4   Region                                1503 non-null   str
 5   SIZE                                  1503 non-null   str
 6   FOCUS                                 1503 non-null   str
 7   RES.                                  1503 non-null   str
 8   STATUS                                1466 non-null   str
 9   Academic_Reputation_Score             1503 non-null   float64
 10  Academic_Reputation_Rank              1503 non-null   str
 11  Employer_Reputation_Score             1503 non-null   float64
 12  Employer_Reputation_Rank              1503 non-null   str
 13  Faculty_Student_Score                 1503 non-null   float64
 14  Faculty_Student_Rank                  1503 non-null   str
 15  Citations_per_Faculty_Score           1503 non-null   float64
 16  Citations_per_Faculty_Rank            1503 non-null   str
 17  International_Faculty_Score           1403 non-null   float64
 18  International_Faculty_Rank            1403 non-null   str
 19  International_Students_Score          1445 non-null   float64
 20  International_Students_Rank           1445 non-null   str
 21  International_Research_Network_Score  1502 non-null   float64
 22  International_Research_Network_Rank   1502 non-null   str
 23  Employment_Outcomes_Score             1503 non-null   float64
 24  Employment_Outcomes_Rank              1503 non-null   str
 25  Sustainability_Score                  1484 non-null   float64
 26  Sustainability_Rank                   1484 non-null   str
 27  Overall_Score                         601 non-null    str
 28  Overall Teaching Score                652 non-null    float64
 29  Research Score                        652 non-null    float64
 30  Research Quality                      652 non-null    float64
 31  Industry Income Score                 652 non-null    float64
 32  International Outlook Score           652 non-null    float64
 33  Overall Score                         652 non-null    float64
 34  Rank                                  652 non-null    float64
dtypes: float64(16), str(19)
memory usage: 411.1 KB

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df = df.drop_duplicates()

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.columns = df.columns.str.strip()

In [16]:
df = df.map(lambda x: x.strip() if isinstance(x, str) else x)

In [17]:
df["University"].head(20)

0           Massachusetts Institute of Technology (MIT)
1                               Imperial College London
2                                  University of Oxford
3                                    Harvard University
4                               University of Cambridge
5                                   Stanford University
6     ETH Zurich - Swiss Federal Institute of Techno...
7                National University of Singapore (NUS)
8                                                   UCL
9          California Institute of Technology (Caltech)
10                           University of Pennsylvania
11             University of California, Berkeley (UCB)
12                          The University of Melbourne
13                                    Peking University
14    Nanyang Technological University, Singapore (NTU)
15                                   Cornell University
16                          The University of Hong Kong
17                             The University of Sydney
18      The University of New South Wales (UNSW Sydney)
19                                  Tsinghua University
Name: University, dtype: str

In [18]:
df["University"].astype(str).str.contains(r"^\s|\s$", regex=True).sum()

np.int64(0)

In [19]:
df["University"] = df["University"].astype(str).str.strip()

In [20]:
df["University"].head(20)

0           Massachusetts Institute of Technology (MIT)
1                               Imperial College London
2                                  University of Oxford
3                                    Harvard University
4                               University of Cambridge
5                                   Stanford University
6     ETH Zurich - Swiss Federal Institute of Techno...
7                National University of Singapore (NUS)
8                                                   UCL
9          California Institute of Technology (Caltech)
10                           University of Pennsylvania
11             University of California, Berkeley (UCB)
12                          The University of Melbourne
13                                    Peking University
14    Nanyang Technological University, Singapore (NTU)
15                                   Cornell University
16                          The University of Hong Kong
17                             The University of Sydney
18      The University of New South Wales (UNSW Sydney)
19                                  Tsinghua University
Name: University, dtype: str

In [21]:
df["Location"].value_counts().head(20)

Location
United States       197
United Kingdom       90
China (Mainland)     71
Japan                49
Germany              48
Russia               47
India                46
South Korea          43
Italy                42
Australia            38
France               35
Brazil               35
Spain                35
Mexico               32
Canada               30
Malaysia             28
Taiwan               27
Indonesia            26
Argentina            25
Chile                25
Name: count, dtype: int64

In [22]:
df["Location"].unique()[:20]

<StringArray>
[   'United States',   'United Kingdom',      'Switzerland',
        'Singapore',        'Australia', 'China (Mainland)',
    'Hong Kong SAR',           'France',           'Canada',
          'Germany',      'South Korea',            'Japan',
      'Netherlands',         'Malaysia',          'Belgium',
      'New Zealand',           'Taiwan',        'Argentina',
           'Sweden',          'Ireland']
Length: 20, dtype: str

In [23]:
df["Location"] = df["Location"].astype(str).str.strip()

In [24]:
df["Location"] = df["Location"].astype(str).str.strip()

In [25]:
df["Location"].astype(str).str.contains(r"^\s|\s$", regex=True).sum()

np.int64(0)

In [26]:
df.isnull().sum()

RANK_2025                                 0
RANK_2024                                21
University                                0
Location                                  0
Region                                    0
SIZE                                      0
FOCUS                                     0
RES.                                      0
STATUS                                   37
Academic_Reputation_Score                 0
Academic_Reputation_Rank                  0
Employer_Reputation_Score                 0
Employer_Reputation_Rank                  0
Faculty_Student_Score                     0
Faculty_Student_Rank                      0
Citations_per_Faculty_Score               0
Citations_per_Faculty_Rank                0
International_Faculty_Score             100
International_Faculty_Rank              100
International_Students_Score             58
International_Students_Rank              58
International_Research_Network_Score      1
International_Research_Network_Rank       1
Employment_Outcomes_Score                 0
Employment_Outcomes_Rank                  0
Sustainability_Score                     19
Sustainability_Rank                      19
Overall_Score                           902
Overall Teaching Score                  851
Research Score                          851
Research Quality                        851
Industry Income Score                   851
International Outlook Score             851
Overall Score                           851
Rank                                    851
dtype: int64

In [27]:
missing_percentage = df.isnull().sum().sum() / df.size * 100
print(missing_percentage)

13.825681969394543

In [28]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage = missing_percentage[missing_percentage > 0].sort_values(ascending=False)

print(missing_percentage)

Overall_Score                           60.013307
Rank                                    56.620093
Research Quality                        56.620093
Research Score                          56.620093
International Outlook Score             56.620093
Overall Score                           56.620093
Overall Teaching Score                  56.620093
Industry Income Score                   56.620093
International_Faculty_Rank               6.653360
International_Faculty_Score              6.653360
International_Students_Rank              3.858949
International_Students_Score             3.858949
STATUS                                   2.461743
RANK_2024                                1.397206
Sustainability_Score                     1.264138
Sustainability_Rank                      1.264138
International_Research_Network_Score     0.066534
International_Research_Network_Rank      0.066534
dtype: float64

In [29]:
df.shape
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [30]:
df.to_csv("university_cleaned.csv", index=False)

In [31]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Overall_Score                           902
Rank                                    851
Research Quality                        851
Research Score                          851
International Outlook Score             851
Overall Score                           851
Overall Teaching Score                  851
Industry Income Score                   851
International_Faculty_Rank              100
International_Faculty_Score             100
International_Students_Rank              58
International_Students_Score             58
STATUS                                   37
RANK_2024                                21
Sustainability_Score                     19
Sustainability_Rank                      19
International_Research_Network_Score      1
International_Research_Network_Rank       1
dtype: int64

In [33]:
numeric_columns = df.select_dtypes(include="number").columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

In [35]:
df.isnull().sum().sum()

np.int64(0)

In [36]:
missing_percentage = df.isnull().sum().sum() / df.size * 100
print(missing_percentage)

0.0

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.isnull().sum().sum()

np.int64(0)

In [40]:
df.shape

(1503, 35)

In [41]:
df.to_csv("university_cleaned.csv", index=False)

In [42]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [45]:
import os

print(os.path.exists("university_cleaned.csv"))

True

In [46]:
df.shape

(1503, 35)

In [47]:
df.head()

,RANK_2025,RANK_2024,University,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,Sustainability_Score,Sustainability_Rank,Overall_Score,Overall Teaching Score,Research Score,Research Quality,Industry Income Score,International Outlook Score,Overall Score,Rank
0,1,1,Massachusetts Institute of Technology (MIT),United States,Americas,M,CO,VH,B,100.0,...,99.0,15=,100,29.4,25.0,64.15,61.9,57.15,47.41,603.0
1,2,6,Imperial College London,United Kingdom,Europe,L,FC,VH,A,98.5,...,99.7,6,98.5,89.3,94.9,98.50,90.8,98.30,94.36,8.0
2,3,3,University of Oxford,United Kingdom,Europe,L,FC,VH,A,100.0,...,85.0,126,96.9,96.8,100.0,98.80,99.6,97.30,98.50,1.0
3,4,4,Harvard University,United States,Americas,L,FC,VH,B,100.0,...,84.4,130,96.8,97.3,99.9,99.30,85.7,90.10,94.46,7.0
4,5,2,University of Cambridge,United Kingdom,Europe,L,FC,VH,A,100.0,...,84.8,127=,96.7,95.9,99.9,97.60,88.4,97.10,95.78,6.0